import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats { 
		
	public static void main (String[] args) {
		int families = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		Random generator = new Random(seed);
		double average = 0;
		String commonKids = "";
		int countTogether = 0;
		int countTwo = 0;
		int countThree = 0;
		int countFourOrMore = 0;
		for (int j = 0; j < families; j++) {
		// Initailizes a random numbers generator with the given seed value
			boolean girl = false;
			boolean boy = false;
			int countEachFamily = 0;
			for (int i=1; !(girl&&boy); i++){
				double random = generator.nextDouble();
				if (random<0.5) {
				boy = true;
				}
				else {
				girl= true;
				}
				countEachFamily+=1;	
		}
		if (countEachFamily==2) {
			countTwo+=1;
		} else if (countEachFamily==3) {
			countThree+=1;
		} else {countFourOrMore+=1;}
		countTogether+=countEachFamily;
		}
		average = (double)countTogether/families;
		double roundedAverage = Math.round(average * 1000.0) / 1000.0;
		Integer mostKidsCheck = Math.max(countTwo,Math.max(countThree,countFourOrMore));
		
		if (mostKidsCheck.equals(countTwo)) {
			commonKids = "2";
		}
		else if (mostKidsCheck.equals(countThree)) {
			commonKids = "3";
		}
		else{ commonKids = "4 or more";}
		
		System.out.println("Average: "+ roundedAverage + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + countTwo);
		System.out.println("Number of families with 3 children: " + countThree);
		System.out.println("Number of families with 4 or more children: " + countFourOrMore);
		System.out.println("The most common number of children is " + commonKids + ".");
		}}
		
		
		    
	

